[project]
name = "Terra App"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  alembic>=1.13.3
  amqp>=5.3.1
  bcrypt>=4.2.0
  billiard>=4.2.1
  blinker>=1.9.0
  branca>=0.8.1
  cachelib>=0.13.0
  celery>=5.5.3
  certifi>=2025.1.31
  chardet>=5.2.0
  charset-normalizer>=3.4.1
  click>=8.1.7
  click-didyoumean>=0.3.1
  click-plugins>=1.1.1.2
  click-repl>=0.3.0
  colorama>=0.4.6
  dnspython>=2.7.0
  email_validator>=2.2.0
  Flask>=3.1.1
  Flask-Bcrypt>=1.0.1
  Flask-Caching>=2.3.1
  Flask-Login>=0.6.3
  Flask-Migrate>=4.0.7
  Flask-SQLAlchemy>=3.1.1
  Flask-WTF>=1.2.2
  folium>=0.19.4
  greenlet>=3.1.1
  gunicorn>=23.0.0
  idna>=3.10
  itsdangerous>=2.2.0
  Jinja2>=3.1.4
  kombu>=5.5.4
  Mako>=1.3.5
  MarkupSafe>=3.0.1
  mysqlclient>=2.2.7
  numpy>=2.2.2
  packaging>=25.0
  pandas>=2.2.3
  pillow>=11.2.1
  prompt_toolkit>=3.0.51
  psycopg2>=2.9.10
  pyodbc>=5.2.0
  python-dateutil>=2.9.0.post0
  python-dotenv>=1.1.0
  python-slugify>=8.0.4
  pytz>=2025.1
  redis>=6.2.0
  reportlab>=4.4.1
  requests>=2.32.3
  resend>=2.11.0
  six>=1.17.0
  SQLAlchemy>=2.0.36
  text-unidecode>=1.3
  typing_extensions>=4.12.2
  tzdata>=2025.2
  urllib3>=2.3.0
  vine>=5.1.0
  wcwidth>=0.2.13
  Werkzeug>=3.1.3
  WTForms>=3.2.1
  xyzservices>=2025.1.0
]