"""updated db

Revision ID: 03c28fbdbfe4
Revises: 8f56decbe5eb
Create Date: 2025-06-11 15:14:26.253874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03c28fbdbfe4'
down_revision = '8f56decbe5eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab-analysis-details',
    sa.Column('lab_analysis_id', sa.Integer(), nullable=True),
    sa.Column('test', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lab_analysis_id'], ['lab-analysis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    with op.batch_alter_table('lab-analysis', schema=None) as batch_op:
        batch_op.drop_column('result')
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab-analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('result', mysql.TEXT(), nullable=False))

    op.drop_table('lab-analysis-details')
    # ### end Alembic commands ###
