"""Updated db

Revision ID: 25bdab64fdad
Revises: cf8bde16486f
Create Date: 2025-06-10 11:26:09.408475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25bdab64fdad'
down_revision = 'cf8bde16486f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.drop_constraint('diagnosis_ibfk_2', type_='foreignkey')
        batch_op.drop_column('disease_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disease_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('diagnosis_ibfk_2', 'disease', ['disease_id'], ['id'])

    # ### end Alembic commands ###
