"""Updated db

Revision ID: 4e0c3105dc5d
Revises: 25bdab64fdad
Create Date: 2025-06-10 15:06:20.764005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e0c3105dc5d'
down_revision = '25bdab64fdad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_closed', sa.DateTime(), nullable=True))

    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_closed', sa.DateTime(), nullable=True))
        batch_op.drop_column('is_closed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_closed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('date_closed')
        batch_op.drop_column('date_created')

    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.drop_column('date_closed')
        batch_op.drop_column('date_created')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
