"""updated db

Revision ID: 629154003a88
Revises: 62a608c467c6
Create Date: 2025-06-09 14:08:41.437974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629154003a88'
down_revision = '62a608c467c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.drop_column('note')

    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
