"""updated db

Revision ID: 8ed0cabf10bc
Revises: decda49401e8
Create Date: 2025-06-11 15:58:19.706638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ed0cabf10bc'
down_revision = 'decda49401e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_analysis',
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_approved', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_table('lab_analysis_details',
    sa.Column('lab_analysis_id', sa.Integer(), nullable=True),
    sa.Column('test', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lab_analysis_id'], ['lab_analysis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    with op.batch_alter_table('lab-analysis', schema=None) as batch_op:
        batch_op.drop_index('unique_id')

    op.drop_table('lab-analysis')
    with op.batch_alter_table('lab-analysis-details', schema=None) as batch_op:
        batch_op.drop_index('unique_id')

    op.drop_table('lab-analysis-details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab-analysis-details',
    sa.Column('lab_analysis_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('test', mysql.TEXT(), nullable=False),
    sa.Column('result', mysql.TEXT(), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('unique_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lab_analysis_id'], ['lab-analysis.id'], name='lab-analysis-details_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('lab-analysis-details', schema=None) as batch_op:
        batch_op.create_index('unique_id', ['unique_id'], unique=True)

    op.create_table('lab-analysis',
    sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('appointment_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_approved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('date_approved', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('unique_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], name='lab-analysis_ibfk_1'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], name='lab-analysis_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('lab-analysis', schema=None) as batch_op:
        batch_op.create_index('unique_id', ['unique_id'], unique=True)

    op.drop_table('lab_analysis_details')
    op.drop_table('lab_analysis')
    # ### end Alembic commands ###
